### ISSUE TITLE
Improve password and secret security in Docker

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon-docker#12]
### Description
Currently we are storing secrets in environment variables; for security reasons we should avoid this. @phuongdh thinks it could be encrytable and rotatable. 

## Done looks like 
 Environmental variables are encrypted and rotating.

**Comment by phuongdh** [comment]
Docker secret is available in Swarm mode, we should look into using it.

**Comment by joncameron** [comment]
If we use CentOS 8 and Podman, this is irrelevant.
