### ISSUE TITLE
Service 'solr' failed to build: Got HTTP status code >= 400: 404 Not Found

### ISSUE THREAD

**Issue by taozhaolib** [avalonmediasystem/avalon-docker#17]
OS X EI Capitan OP system. Run as instructed in the README file:

Building solr
Step 1 : FROM solr:6.1.0-alpine
6.1.0-alpine: Pulling from library/solr
b7f33cc0b48e: Pull complete
43a564ae36a3: Pull complete
efb75a810eee: Pull complete
c4d212fb289f: Pull complete
3faed70a1c93: Pull complete
266702a1d22c: Pull complete
ec13ad37b923: Pull complete
c781698b5202: Pull complete
28722d3192cd: Pull complete
b0d331a91d77: Pull complete
6e407011ae09: Pull complete
Digest: sha256:240f73c4c642bffc64529abbde2cffba7491f8f96297f12b7ba10478820f741b
Status: Downloaded newer image for solr:6.1.0-alpine
 ---> e955a313d516
Step 2 : MAINTAINER Michael B. Klein <michael.klein@northwestern.edu>
 ---> Running in 889e2d4e1788
 ---> db11663542b9
Removing intermediate container 889e2d4e1788
Step 3 : ARG AVALON_BRANCH=develop
 ---> Running in e07ca80008f7
 ---> 7be48fe5eb92
Removing intermediate container e07ca80008f7
Step 4 : ADD https://raw.githubusercontent.com/avalonmediasystem/avalon/${AVALON_BRANCH}/solr/config/schema.xml avalon_conf/
ERROR: Service 'solr' failed to build: Got HTTP status code >= 400: 404 Not Found
LIBC02MR1QVFD59:avalon-docker zhao0677$ docker-machine stop default
Stopping "default"...
Machine "default" was stopped.

**Comment by phuongdh** [comment]
@taozhaolib what does your .env file look like?

**Comment by taozhaolib** [comment]
As told, I copied the dotenv.example to .env and fill in the passwords and Rails secrect key base.

it is like this:

# Required Settings
APP_NAME=avalon
BASE_URL=http://localhost:8888/
STREAMING_HOST=localhost
AVALON_DB_PASSWORD=avalon
FEDORA_DB_PASSWORD=fedora
SECRET_KEY_BASE=9489b3eee4eccf317ed77407553e8adc97baca7c74dc7ee33cd93e4c8b69477eea66eaedeb18af0be2679887c7c69c0a28c0fded0a71ea472a8c4laalal19cb

# Recommended Settings
EMAIL_COMMENTS=avalon-comments@example.edu
EMAIL_NOTIFICATION=avalon-notifications@example.edu
EMAIL_SUPPORT=avalon-support@example.edu
SMTP_ADDRESS=smtp.example.edu
SMTP_PORT=587

# Optional Settings
# Z3950_HOST=
# Z3950_PORT=
# Z3950_DATABASE=
# Z3950_ATTRIBUTE=
# LTI_AUTH_KEY=
# LTI_AUTH_SECRET=

I put a random secret key value in this file, not sure if this is the correct way to do.

Thanks!

**Comment by phuongdh** [comment]
Can you try putting AVALON_BRANCH=develop (or master if that's what you're going for) in the .env file and run again? Btw, you can also simply run `docker-compose pull` before `docker-compose up` to get the prebuilt images from Dockerhub, if you don't want to build the images yourself.

**Comment by taozhaolib** [comment]
Another question:

I also tried to install on a Centos vagrant box by following the instructions. It is looking good now. Could you please list all the different services with port numbers for this installation, as what you did for OS X installation? Thanks.

**Comment by taozhaolib** [comment]
After I added the AVALON_BRANCH=develop, ran docker-compose pull before docker-compose up, I found another error message that seemed to be a docker issue but I have not found a solution yet:

Creating avalondocker_hls_1
Creating avalondocker_rtmp_1
Creating avalondocker_db_1
Creating avalondocker_redis_1
Creating avalondocker_matterhorn_1
Creating avalondocker_solr_1

ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint avalondocker_db_1 (05df176dcf330044b5bf7fef538735bada6d8fa7faac43b6733c2c9e83c2a725): Error starting userland proxy: Bind for 0.0.0.0:5432 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.

Wonder if you guys have ever seen this.

Thanks.

**Comment by phuongdh** [comment]
I don't have a Mac but this may be relevant: https://github.com/avalonmediasystem/avalon-docker/blob/development/networking.md

**Comment by taozhaolib** [comment]
I changed the port number 5432 to 5555 and fixed this issue. But when I re-ran "docker-compose up", I got this message kept being printed on the screen:

" hls_1         | nginx: [emerg] invalid value "thumb" in "vod" directive, it must be one of: none,dash,hds,hls,mss in /etc/nginx/nginx.conf:60"

Again, all the problems happened on OSX installation. The linux installation was great. I ran it in the vagrant box only once and it worked.

**Comment by phuongdh** [comment]
@taozhaolib I'm not sure what's going on there. @mbklein may be able to help you.

**Comment by phuongdh** [comment]
@taozhaolib do you have an update on this issue?

**Comment by taozhaolib** [comment]
I could not reach @mbklein so the problem is still there.

**Comment by joncameron** [comment]
Closing this as it's been a few years since being reported. Based on the log above it might the branch  variable in the URL https://raw.githubusercontent.com/avalonmediasystem/avalon/${AVALON_BRANCH}/solr/config/schema.xml.
