### ISSUE TITLE
Error Starting avalon_avalon_1

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon-docker#42]
## Environment
macOS 10.14.6, Docker Desktop 2.1.0.3
Using instructions in the Avalon readme, Master branch (6.5.0)

## Error

Starting avalon_matterhorn_1 ... done
Starting avalon_redis_1      ... done
Starting avalon_hls_1        ... done
Starting avalon_solr_1       ... done
Starting avalon_db_1         ... done
Starting avalon_fedora_1     ... done
Starting avalon_avalon_1     ... error

ERROR: for avalon_avalon_1  Cannot start service avalon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/rails_init-dev.sh\": stat /rails_init-dev.sh: no such file or directory": unknown

ERROR: for avalon  Cannot start service avalon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/rails_init-dev.sh\": stat /rails_init-dev.sh: no such file or directory": unknown
ERROR: Encountered errors while bringing up the project.

**Comment by cjcolvar** [comment]
@joncameron Has this been resolved?

**Comment by joncameron** [comment]
@cjcolvar It's broken on master, but on develop works fine. I'm going to close. Since we're not pivoting to Docker for evaluation at the moment I think this is OK, since it's explicitly for dev work.
