### ISSUE TITLE
invite user fail - Hostname not known: mail-relay.university.edu

### ISSUE THREAD

**Issue by rstanonik** [avalonmediasystem/avalon-docker#47]
I just installed avalon-docker 7.1.0

Invite User fails with this in the log

avalon_1  | F, [2020-05-25T14:10:27.604672 #1] FATAL -- : SocketError (Hostname not known: mail-relay.university.edu):

.env contains
SMTP_ADDRESS=smtp.ucsd.edu

But that is not being used

Thanks,
Ron

**Comment by joncameron** [comment]
@phuongdh will check on this.

**Comment by rstanonik** [comment]
I was able to get the invite working by adding

docker-compose.yml
+      - SETTINGS__EMAIL__CONFIG__ADDRESS

and setting

.env
SETTINGS__EMAIL__CONFIG__ADDRESS=smtp.ucsd.edu
SETTINGS__EMAIL__NOTIFICATION=avalon-notifications@ucsd.edu

**Comment by phuongdh** [comment]
@rstanonik that's the right way to do it 👏
