### ISSUE TITLE
Make S3-helper streaming links last longer

### ISSUE THREAD

**Issue by SolomonHD** [avalonmediasystem/avalon-docker#51]
Currently when using s3 helper generated streaming links, if the user pauses a video for an hour, then resumes and scans forward, to a section of the video not cached, avalon will error out because its link to download the video has expired. The video cannot be streamed again until the page is reloaded.

Please see if you can increase the expiration time of the generated links. I don't know what the AWS maximum is but I would assume it's at least 6 hours.

**Comment by joncameron** [comment]
We'll need to investigate where the timeout is happening. If it's on the presigned URL, there will be more tinkering with evs-s3-helper code. If it's somewhere else, it may be easier to set a new timeout value.

**Comment by phuongdh** [comment]
@SolomonHD stream token expires in 20 minutes by default, have you tried changing this setting? https://github.com/avalonmediasystem/avalon/blob/master/config/settings.yml#L47

**Comment by SolomonHD** [comment]
Changing the setting fixed our issue.
