### ISSUE TITLE
Add volume and config for supplemental files

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon-docker#56]

**Comment by Dananji** [comment]
I uploaded new supplemental and transcript files and I'm able to download them in item page!
But the existing files cannot be downloaded. And I get the following error:

![Screenshot from 2021-04-19 13-56-26.png](https://images.zenhubusercontent.com/5cc1c66b3244e00362de97ea/20da4354-997c-4f63-bb02-2bff53365902)

@apertome With this change do we need to migrate the existing supplemental files? Is this a concern when we deploy this to production (if there are supplemental files in the system) ?

**Comment by apertome** [comment]
@Dananji We either need to migrate the existing files or find a way to fall back to the old location if not found. Where were they stored previously?

**Comment by joncameron** [comment]
There should be another fix to resolve this.
