### ISSUE TITLE
Can it be published as a virtual machine

### ISSUE THREAD

**Issue by zhangyilibecnu** [avalonmediasystem/avalon-docker#68]
I have installed it many times using docker, and there are various problems. I have been trying for many days, whether it can be released as a virtual machine, so that I can directly experience it locally, eliminating the problem of docker installation.

**Comment by cjcolvar** [comment]
I'm sorry that you've been having issues with the docker install.  We previously published a virtual machine but have discontinued that in favor of containerization and the docker-compose configuration.  If you want to explore Avalon without installing locally, you can try https://demo.avalonmediasystem.org and request a privileged account to upload and edit content.  (See https://www.avalonmediasystem.org/try-out-avalon for details.)
