### ISSUE TITLE
Investigate using CloudSearch's Solr

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon-docker#7]

**Comment by phuongdh** [comment]
Blacklight uses Solr for search, Hydra uses it for gated discovery and some other things.

For Blacklight: either shim rsolr to work with their request/response formats, or some work in blacklight to build a new `Blacklight::Repository` that supports it. (cbeer)
For Hydra: not sure, may be a lot of work.

Indexing: need to use AWS Ruby library CloudSearch http://docs.aws.amazon.com/sdkforruby/api/Aws/CloudSearch.html

**Comment by davidschober** [comment]
@mbklein can you take a look at these notes and close it? It sounds non trivial.

**Comment by davidschober** [comment]
Completed, we will pick this up in summer. It's a medium pain.
