### ISSUE TITLE
Investigate Supplemental File Storage

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon-docker#77]
# Description
When running the supplemental file migration I noticed that ActiveStorage wasn't configured to point to s3.  This means that all of the actual binaries were lost (probably a while ago) when the container restarted since it was storing it locally in the container and not even in a volume.  I configured ActiveStorage so all newly created supplemental files should be persisted correctly but I'm concerned that this data loss has happened for other out of the box docker installs.

It also seems like there might be something wrong with transcripts showing up in ramp on the demo site.  I'll look into it more tomorrow.

# Done Looks Like
- [ ] Investigation of how this is configured and what needs to change to avoid potential data loss

**Comment by cjcolvar** [comment]
It appears that out of the box avalon-docker does not use minio and instead bind mounts a local directory to use for ActiveStorage's `:local` configuration.  This means that the issue is isolated to the `aws_min` branch used by `avalon-terraform`.  I'll come up with instructions for trying to salvage supplemental files and migrate to the `:s3` ActiveStorage configuration and then add it to the upgrade instructions (as well as tell Emory).

**Comment by cjcolvar** [comment]
Steps for salvaging files before upgrade/restart should be something like:
```
# Copy files out of docker container to local directory
docker cp avalon-docker-aws_min_avalon_1:/home/app/avalon/storage ./active_storage_backup
# Copy files to s3 bucket
aws s3 cp active_storage_backup/* s3://${SETTINGS__ACTIVE_STORAGE__BUCKET}/ --recursive 
```

**Comment by cjcolvar** [comment]
PRs merged and warning added to Avalon 7.7->7.8 upgrade wiki page.

@joncameron Should a note be sent out to the Avalon community soon with a warning?

**Comment by nepella** [comment]
@cjcolvar: The `avalon-docker-aws_min-avalon-1` containers for our Terraform deployment (based on v7.6) don't have a `/home/app/avalon/storage` directory. Can I rely on that to indicate that we're not affected?

Do you know off the top of your head why our deployment has the container's name ending in `-1`, not `_1`?

Thanks!

**Comment by cjcolvar** [comment]
@nepella You might be safe, but I'd check the running app's configuration is S3 and that you see files in the listed bucket (if you have any supplemental files).
```
docker-compose exec avalon /bin/bash -c "RAILS_ENV=production bundle exec rails r 'puts Rails.application.config.active_storage.service_configurations[Rails.application.config.active_storage.service.to_s]'"
```

**Comment by joncameron** [comment]
Messaging has gone out to at this point to all channels and documentation updated.
