### ISSUE TITLE
S3 storage for master files, derivatives and dropbox

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon-docker#9]
### Description
AWS storage for files needs to be discussed.

### Decision point
- [ ] What are we going to do?
- [ ] Create plan for moving forward and write new tickets as needed.

**Comment by davidschober** [comment]
note avalon/#1721 might not need to be done if we decide to use s3 with a lambda to do ingestion.

**Comment by mcwhitaker** [comment]
@phuongdh @mbklein   I discussed this topic today with Jon D and he said that for the SaaS pilot we will use duracloud for storage of master files.
